=== kalodaniel/BBKHXF_XMLGyak/BBKHXF_09.28/KD_konyv.dtd
<!ELEMENT konyvek (konyv)+>
<!ELEMENT cim (#PCDATA)>
<!ELEMENT kiadas (#PCDATA)>
<!ELEMENT kiado (#PCDATA)>
<!ELEMENT szerzo (#PCDATA)>
<!ELEMENT konyv (cim,kiadas,kiado,szerzok)+>
<!ATTLIST konyv xmlns CDATA #FIXED '' id CDATA #REQUIRED>
<!ELEMENT szerzok (szerzo)+>

=== kalodaniel/BBKHXF_XMLGyak/BBKHXF_09.28/KD_konyv.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE konyvek SYSTEM "KD_konyv.dtd">
<konyvek>
    <konyv id="1">
        <cim>Android zsebkönyv</cim>
        <kiadas>2019.10.28</kiadas>
        <kiado>Libri</kiado>
        <szerzok>
            <szerzo>Bártfai Barnabás</szerzo>
        </szerzok>
    </konyv>
    <konyv id="2">
        <cim>Pragmatic Programmer</cim>
        <kiadas>2015.03.13</kiadas>
        <kiado>Libri</kiado>
        <szerzok>
            <szerzo>Davis Thomas</szerzo>
            <szerzo>Andrew Hunt</szerzo>
        </szerzok>
    </konyv>
    <konyv id="3">
        <cim>Limitless</cim>
        <kiadas>2016.04.11</kiadas>
        <kiado>Libri</kiado>
        <szerzok>
            <szerzo>Jim Kwik</szerzo>
        </szerzok>
    </konyv>
</konyvek>
