=== kalodaniel/BBKHXF_XMLGyak/BBKHXF_09.28/KD_orarend.dtd
<?xml version="1.0" encoding="UTF-8" ?>

<!ELEMENT orarend (ora)*>
<!ELEMENT ora (targy?,idopont+,helyszin+,oktato+,szak)*>
        <!ATTLIST ora id ID #REQUIRED>
        <!ATTLIST ora tipus (ElmÃ©let|Gyakorlat) #REQUIRED>
        <!ELEMENT targy (#PCDATA)>
        <!ELEMENT idopont (#PCDATA)>
        <!ELEMENT helyszin (#PCDATA)>
        <!ELEMENT oktato (#PCDATA)>
        <!ELEMENT szak (#PCDATA)>

=== kalodaniel/BBKHXF_XMLGyak/BBKHXF_09.28/KD_orarend.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE orarend SYSTEM "KD_orarend.dtd">

<orarend>
    <ora id="a01" tipus="Gyakorlat">
        <targy>Webes Alkalmazások</targy>
        <idopont>Hétfő 10-12</idopont>
        <helyszin>Miskolci Egyetem</helyszin>
        <oktato>Krizsán Zoltán</oktato>
        <szak>Mérnök informatikus</szak>
    </ora>
    <ora id="a02" tipus="Elmélet">
        <targy>Web technológiák</targy>
        <idopont>Hétfő 12-14</idopont>
        <helyszin>Miskolci Egyetem</helyszin>
        <oktato>Agárdi Anita</oktato>
        <szak>Mérnök informatikus</szak>
    </ora>
    <ora id="a03" tipus="Elmélet">
        <targy>Mesterséges Intelligencia</targy>
        <idopont>Hétfő 14-17</idopont>
        <helyszin>Miskolci Egyetem</helyszin>
        <oktato>Dudás Laszló</oktato>
        <szak>Mérnök informatikus</szak>
    </ora>
    <ora id="a04" tipus="Gyakorlat">
        <targy>Webes Alkalmazások</targy>
        <idopont>Kedd 10-12</idopont>
        <helyszin>Miskolci Egyetem</helyszin>
        <oktato>Krizsán Zoltán</oktato>
        <szak>Mérnök informatikus</szak>
    </ora>
    <ora id="a05" tipus="Elmélet">
        <targy>Adatkezelés XML-ben</targy>
        <idopont>Kedd 12-14</idopont>
        <helyszin>Miskolci Egyetem</helyszin>
        <oktato>Bednarik László</oktato>
        <szak>Mérnök informatikus</szak>
    </ora>
    <ora id="a06" tipus="Gyakorlat">
        <targy>Adatkezelés XML-ben</targy>
        <idopont>Kedd 14-16</idopont>
        <helyszin>Miskolci Egyetem</helyszin>
        <oktato>Bednarik László</oktato>
        <szak>Mérnök informatikus</szak>
    </ora>
    <ora id="a07" tipus="Gyakorlat">
        <targy>Web technológiák</targy>
        <idopont>Kedd 16-18</idopont>
        <helyszin>Miskolci Egyetem</helyszin>
        <oktato>Agárdi Anita</oktato>
        <szak>Mérnök informatikus</szak>
    </ora>
    <ora id="a08" tipus="Gyakorlat">
        <targy>Mesterséges Intelligencia</targy>
        <idopont>Kedd 18-19</idopont>
        <helyszin>Miskolci Egyetem</helyszin>
        <oktato>Dudás László</oktato>
        <szak>Mérnök informatikus</szak>
    </ora>
    <ora id="a09" tipus="Elmélet">
        <targy>Szoftvertesztelés</targy>
        <idopont>Szerda 8-10</idopont>
        <helyszin>Miskolci Egyetem</helyszin>
        <oktato>Tompa Tamás</oktato>
        <szak>Mérnök informatikus</szak>
    </ora>
    <ora id="a10" tipus="Gyakorlat">
        <targy>Szoftvertesztelés</targy>
        <idopont>Szerda 10-12</idopont>
        <helyszin>Miskolci Egyetem</helyszin>
        <oktato>Tompa Tamás</oktato>
        <szak>Mérnök informatikus</szak>
    </ora>
    <ora id="a11" tipus="Elmélet">
        <targy>Integrál Vállalati Rendszerek</targy>
        <idopont>Szerda 14-16</idopont>
        <helyszin>Miskolci Egyetem</helyszin>
        <oktato>Samad Dadvandipour</oktato>
        <szak>Mérnök informatikus</szak>
    </ora>
    <ora id="a12" tipus="Gyakorlat">
        <targy>Integrált Vállalati Rendszerek</targy>
        <idopont>Szerda 16-18</idopont>
        <helyszin>Miskolci Egyetem</helyszin>
        <oktato>Samad Dadvandipour</oktato>
        <szak>Mérnök informatikus</szak>
    </ora>
</orarend>
