=== kalodaniel/BBKHXF_XMLGyak/Feleves feladatok/1.Feladat/XMLSchemaBBKHXF.xsd
<?xml version="1.0" encoding="utf-8" ?>

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="qualified">
    <xs:element name="autocentrum" type="autocentrumTipus">
        <xs:key name = "autoPK">
            <xs:selector xpath="auto"/>
            <xs:field xpath="autoId"/>
        </xs:key>
        <xs:key name = "megrendeloPK">
            <xs:selector xpath="megrendelo"/>
            <xs:field xpath="megrendeloId"/>
        </xs:key>
        <xs:key name = "rendelesPK">
            <xs:selector xpath="rendeles"/>
            <xs:field xpath="rendelesId"/>
        </xs:key>
        <xs:key name = "beszallitoPK">
            <xs:selector xpath="beszallito"/>
            <xs:field xpath="beszallitoId"/>
        </xs:key>
        <xs:key name = "kereskedesPK">
            <xs:selector xpath="kereskedes"/>
            <xs:field xpath="kereskedesId"/>
        </xs:key>
        <xs:key name = "dolgozoPK">
            <xs:selector xpath="dolgozo"/>
            <xs:field xpath="dolgozoId"/>
        </xs:key>
        <xs:key name = "szamlaPK">
            <xs:selector xpath="szamla"/>
            <xs:field xpath="szamlaId"/>
        </xs:key>
        <xs:keyref refer="autoPK" name = "vasarlasAutoFK">
            <xs:selector xpath="vasarlas"/>
            <xs:field xpath="autoFk"/>
        </xs:keyref>
        <xs:keyref refer="megrendeloPK" name = "vasarlasMegrendeloFK">
            <xs:selector xpath="vasarlas"/>
            <xs:field xpath="megrendeloFk"/>
        </xs:keyref>
        <xs:keyref refer="autoPK" name = "rendelesAutoFK">
            <xs:selector xpath="rendeles"/>
            <xs:field xpath="autoFk"/>
        </xs:keyref>
        <xs:keyref refer="beszallitoPK" name = "rendelesBeszallitoFK">
            <xs:selector xpath="rendeles"/>
            <xs:field xpath="beszallitoFk"/>
        </xs:keyref>
        <xs:keyref refer="kereskedesPK" name = "foglalkoztatasKereskedesFK">
            <xs:selector xpath="foglalkoztatas"/>
            <xs:field xpath="kereskedesFk"/>
        </xs:keyref>
        <xs:keyref refer="dolgozoPK" name = "foglalkoztatasDolgozoFK">
            <xs:selector xpath="foglalkoztatas"/>
            <xs:field xpath="dolgozoFk"/>
        </xs:keyref>
    </xs:element>

    <xs:complexType name="autocentrumTipus">
        <xs:sequence>
            <xs:element name="auto" type="autoTipus" minOccurs="0" maxOccurs="unbounded"/>
            <xs:element name="vasarlas" type="vasarlasTipus" minOccurs="0" maxOccurs="unbounded"/>
            <xs:element name="megrendelo" type="megrendeloTipus" minOccurs="0" maxOccurs="unbounded"/>
            <xs:element name="rendeles" type="rendelesTipus" minOccurs="0" maxOccurs="unbounded"/>
            <xs:element name="beszallito" type="beszallitoTipus" minOccurs="0" maxOccurs="unbounded"/>
            <xs:element name="kereskedes" type="kereskedesTipus" minOccurs="0" maxOccurs="unbounded"/>
            <xs:element name="foglalkoztatas" type="foglalkoztatasTipus" minOccurs="0" maxOccurs="unbounded"/>
            <xs:element name="dolgozo" type="dolgozoTipus" minOccurs="0" maxOccurs="unbounded"/>
            <xs:element name="szamla" type="szamlaTipus" minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="autoTipus">
        <xs:sequence>
            <xs:element name="autoId" type="xs:integer"/>
            <xs:element name="ar" type="xs:double"/>
            <xs:element name="szin" type="xs:string"/>
            <xs:element name="hajtas" type="xs:string" maxOccurs="unbounded"/>
            <xs:element name="extrak" type="xs:string" maxOccurs="unbounded"/>
            <xs:element name="motor" type="motorTipus"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="motorTipus">
        <xs:sequence>
            <xs:element name="hengerurtartalom" type="xs:integer"/>
            <xs:element name="teljesitmeny" type="xs:integer"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="vasarlasTipus">
        <xs:sequence>
            <xs:element name="autoFk" type="xs:integer"/>
            <xs:element name="darabszam" type="xs:integer"/>
            <xs:element name="fizetesimod" type="xs:string"/>
            <xs:element name="megrendeloFK" type="xs:integer"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="megrendeloTipus">
        <xs:sequence>
            <xs:element name="megrendeloId" type="xs:integer"/>
            <xs:element name="nev" type="xs:string"/>
            <xs:element name="cim" type="cimTipus"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="cimTipus">
        <xs:sequence>
            <xs:element name="iranyitoszam" type="xs:integer"/>
            <xs:element name="telepules" type="xs:string"/>
            <xs:element name="utca" type="xs:string"/>
            <xs:element name="hazszam" type="xs:string"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="rendelesTipus">
        <xs:sequence>
            <xs:element name="rendelesId" type="xs:integer"/>
            <xs:element name="datum" type="xs:date"/>
            <xs:element name="darabszam" type="xs:integer"/>
            <xs:element name="autoFk" type="xs:integer"/>
            <xs:element name="beszallitoFk" type="xs:integer"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="beszallitoTipus">
        <xs:sequence>
            <xs:element name="beszallitoId" type="xs:integer"/>
            <xs:element name="elerhetoseg" type="xs:string" maxOccurs="unbounded"/>
            <xs:element name="markanev" type="xs:string"/>
            <xs:element name="cim" type="cimTipus"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="kereskedesTipus">
        <xs:sequence>
            <xs:element name="kereskedesId" type="xs:integer"/>
            <xs:element name="autojellemzok" type="xs:string"/>
            <xs:element name="tartalmaz" type="xs:boolean"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="foglalkoztatasTipus">
        <xs:sequence>
            <xs:element name="kereskedesFk" type="xs:integer"/>
            <xs:element name="dolgozoFk" type="xs:integer"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="dolgozoTipus">
        <xs:sequence>
            <xs:element name="dolgozoId" type="xs:integer"/>
            <xs:element name="beosztas" type="xs:string" />
            <xs:element name="fizetes" type="xs:integer"/>
            <xs:element name="cim" type="cimTipus"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="szamlaTipus">
        <xs:sequence>
            <xs:element name="szamlaId" type="xs:integer"/>
            <xs:element name="datum" type="xs:date"/>
            <xs:element name="osszeg" type="xs:integer"/>
        </xs:sequence>
    </xs:complexType>
</xs:schema>

=== kalodaniel/BBKHXF_XMLGyak/Feleves feladatok/1.Feladat/XMLbbkhxf.xml
<?xml version="1.0" encoding="utf-8" ?>

<autocentrum xsi:noNamespaceSchemaLocation="XMLSchemaBBKHXF.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
    <auto>
        <autoId>1</autoId>
        <ar>12000000</ar>
        <szin>Fekete</szin>
        <hajtas>Osszkerek</hajtas>
        <extrak>Ulesfutes</extrak>
        <extrak>Savtarto</extrak>
        <motor>
            <hengerurtartalom>1300</hengerurtartalom>
            <teljesitmeny>100</teljesitmeny>
        </motor>
    </auto>
    <auto>
        <autoId>2</autoId>
        <ar>16000000</ar>
        <szin>Feher</szin>
        <hajtas>Osszkerek</hajtas>
        <hajtas>Hatsokerek</hajtas>
        <extrak>Ulesfutes</extrak>
        <extrak>Savtarto</extrak>
        <extrak>Kormenyfutes</extrak>
        <motor>
            <hengerurtartalom>1600</hengerurtartalom>
            <teljesitmeny>160</teljesitmeny>
        </motor>
    </auto>
    <vasarlas>
        <autoFk>1</autoFk>
        <darabszam>1</darabszam>
        <fizetesimod>Kartyas</fizetesimod>
        <megrendeloFK>1</megrendeloFK>
    </vasarlas>
    <vasarlas>
        <autoFk>1</autoFk>
        <darabszam>1</darabszam>
        <fizetesimod>Keszpenz</fizetesimod>
        <megrendeloFK>1</megrendeloFK>
    </vasarlas>
    <megrendelo>
        <megrendeloId>1</megrendeloId>
        <nev>Kiss √Åkos</nev>
        <cim>
            <iranyitoszam>3400</iranyitoszam>
            <telepules>Mezokovesd</telepules>
            <utca>Szomolyai</utca>
            <hazszam>12</hazszam>
        </cim>
    </megrendelo>
    <rendeles>
        <rendelesId>1</rendelesId>
        <datum>2021-02-04</datum>
        <darabszam>5</darabszam>
        <autoFk>1</autoFk>
        <beszallitoFk>1</beszallitoFk>
    </rendeles>
    <beszallito>
        <beszallitoId>1</beszallitoId>
        <elerhetoseg>0620/113-5264</elerhetoseg>
        <elerhetoseg>beszallito@gmail.com</elerhetoseg>
        <markanev>Ferrari</markanev>
        <cim>
            <iranyitoszam>3500</iranyitoszam>
            <telepules>Miskolc</telepules>
            <utca>Tapolcai</utca>
            <hazszam>45</hazszam>
        </cim>
    </beszallito>
    <kereskedes>
        <kereskedesId>1</kereskedesId>
        <autojellemzok>Kombi</autojellemzok>
        <tartalmaz>1</tartalmaz>
    </kereskedes>
    <foglalkoztatas>
        <kereskedesFk>1</kereskedesFk>
        <dolgozoFk>1</dolgozoFk>
    </foglalkoztatas>
    <dolgozo>
        <dolgozoId>1</dolgozoId>
        <beosztas>Uzletvezeto</beosztas>
        <fizetes>400000</fizetes>
        <cim>
            <iranyitoszam>3400</iranyitoszam>
            <telepules>Mezokovesd</telepules>
            <utca>Hovirag</utca>
            <hazszam>11</hazszam>
        </cim>
    </dolgozo>
    <szamla>
        <szamlaId>1</szamlaId>
        <datum>2020-12-03</datum>
        <osszeg>13000000</osszeg>
    </szamla>
</autocentrum>
